{"external": false, "compiler_defines": "", "link_always": false, "exclude_from_build": false, "enable_system_call": false}
//This function gets only the needed bits of a variable
// |**Version**|**Author**| **Date** |**Changes**
// | 1         | NSN      | 16-03-22 | Creation
FUNCTION FU_iBitGetPart : INT
VAR_INPUT
	value			:INT;		//Variable to get value from
	amount			:BYTE;		//Amount of bits to change
	offset			:BYTE;		//Offset in variable to change bits at
END_VAR
!__IMPLEMENTATION__!
FU_iBitGetPart		:=		TO_INT(SHR(TO_UINT(value),offset) AND TO_UINT(GConstants.binaryMaskInt[amount]));