TYPE SdwBits :
STRUCT
	bit0		:BIT;
	bit1		:BIT;
	bit2		:BIT;
	bit3		:BIT;
	bit4		:BIT;
	bit5		:BIT;
	bit6		:BIT;
	bit7		:BIT;
	bit8		:BIT;
	bit9		:BIT;
	bit10		:BIT;
	bit11		:BIT;
	bit12		:BIT;
	bit13		:BIT;
	bit14		:BIT;
	bit15		:BIT;
	bit16		:BIT;
	bit17		:BIT;
	bit18		:BIT;
	bit19		:BIT;
	bit20		:BIT;
	bit21		:BIT;
	bit22		:BIT;
	bit23		:BIT;
	bit24		:BIT;
	bit25		:BIT;
	bit26		:BIT;
	bit27		:BIT;
	bit28		:BIT;
	bit29		:BIT;
	bit30		:BIT;
	bit31		:BIT;
END_STRUCT
END_TYPE
